### ISSUE TITLE
saran judges

### ISSUE THREAD

**Issue by gunturyogatama404** [zeeid/PHP-Simpel-Proxy-Checker#1]
saran pake judges bang http://httpheader.net/azenv.php biar lebih cepet ngeceknya

**Comment by zeeid** [comment]
@gunturyogatama404 
iya bisa, tapi tujuan ku buat ini buat check proxy bisa lewatin google atau cloudflare (lewat Ouo) atau ngk hehe 😁🙏

tapi boleh jg sarannya buat next fitur
